apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendation-service
  namespace: ml-services
spec:
  replicas: 3
  selector:
    matchLabels:
      app: recommendation-engine
  template:
    metadata:
      labels:
        app: recommendation-engine
    spec:
      containers:
      - name: recommendation-engine
        image: recommendation-engine:latest
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "4Gi"
            cpu: "2000m"
          limits:
            memory: "8Gi"
            cpu: "4000m"
        env:
        - name: MODEL_PATH
          value: "/models/recommendation"
        - name: REDIS_URL
          value: "redis://redis:6379"
        - name: VECTOR_DB_URL
          valueFrom:
            secretKeyRef:
              name: vector-db-secrets
              key: url
        volumeMounts:
        - name: model-storage
          mountPath: /models
        - name: config-volume
          mountPath: /app/config
      volumes:
      - name: model-storage
        persistentVolumeClaim:
          claimName: model-storage-pvc
      - name: config-volume
        configMap:
          name: recommendation-config 