# Model Configuration
model:
  name: credit_risk_scorer
  type: xgboost
  params:
    max_depth: 6
    learning_rate: 0.1
    n_estimators: 200
    subsample: 0.8
    colsample_bytree: 0.8
    
# Feature Configuration
features:
  categorical:
    - loan_purpose
    - employment_type
    - housing_status
  numerical:
    - income
    - debt_to_income
    - credit_score
    - loan_amount
  engineered:
    - payment_ratio
    - credit_utilization
    - debt_burden

# Training Configuration
training:
  test_size: 0.2
  random_state: 42
  cv_folds: 5
  early_stopping_rounds: 10 