apiVersion: apps/v1
kind: Deployment
metadata:
  name: market-analysis-service
  namespace: trading
spec:
  replicas: 3
  selector:
    matchLabels:
      app: market-analysis
  template:
    metadata:
      labels:
        app: market-analysis
    spec:
      containers:
      - name: market-analysis
        image: market-analysis:latest
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
        env:
        - name: DATA_SOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: market-config
              key: data_source_url
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: market-secrets
              key: api_key
        volumeMounts:
        - name: model-volume
          mountPath: /models
        - name: config-volume
          mountPath: /app/config
      volumes:
      - name: model-volume
        persistentVolumeClaim:
          claimName: model-storage
      - name: config-volume
        configMap:
          name: market-config 