version: '3.8'

services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - MODEL_PATH=/models/credit_risk_model
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    volumes:
      - ./models:/models
    depends_on:
      - mlflow
      - prometheus

  mlflow:
    image: mlflow:latest
    ports:
      - "5000:5000"
    environment:
      - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
    volumes:
      - mlflow-data:/mlflow

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./config/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./config/monitoring/grafana-dashboards:/var/lib/grafana/dashboards
      - grafana-data:/var/lib/grafana

volumes:
  mlflow-data:
  prometheus-data:
  grafana-data: 