name: Credit Risk Model Training

on:
  schedule:
    - cron: '0 0 * * 0'  # Weekly on Sunday
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        cd projects/credit_risk
        pip install -r requirements.txt
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    
    - name: Download training data
      run: |
        aws s3 cp s3://credit-risk-data/training/ data/training/ --recursive
    
    - name: Train model
      run: |
        python src/training/train_model.py --config config/model_config.yaml
    
    - name: Evaluate and register model
      run: |
        python src/evaluation/evaluate_model.py
        python src/model/register_model.py
    
    - name: Upload metrics
      uses: actions/upload-artifact@v3
      with:
        name: model-metrics
        path: metrics/ 