groups:
- name: patient_outcome_alerts
  rules:
  - alert: LowPredictionAccuracy
    expr: |
      avg_over_time(patient_outcome_accuracy{timeframe="7d"}[24h]) < 0.80
    for: 1h
    labels:
      severity: warning
    annotations:
      summary: Low prediction accuracy detected
      description: Model accuracy has dropped below 80% over the last 24 hours

  - alert: HighLatency
    expr: |
      histogram_quantile(0.95, 
        rate(patient_outcome_prediction_seconds_bucket[5m])
      ) > 2
    for: 10m
    labels:
      severity: warning
    annotations:
      summary: High prediction latency
      description: 95th percentile of prediction latency is above 2 seconds

  - alert: FeatureDrift
    expr: |
      patient_feature_drift > 0.3
    for: 1h
    labels:
      severity: warning
    annotations:
      summary: Significant feature drift detected
      description: Feature distribution drift score exceeds threshold 