name: Fraud Detection CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'projects/fraud_detection/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'projects/fraud_detection/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        cd projects/fraud_detection
        pip install -r requirements.txt
        pip install pytest pytest-cov
    
    - name: Run tests
      run: |
        cd projects/fraud_detection
        pytest tests/ --cov=src --cov-report=xml
    
    - name: Upload coverage
      uses: codecov/codecov-action@v3
      with:
        file: ./projects/fraud_detection/coverage.xml

  deploy:
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    
    - name: Build and push Docker image
      run: |
        cd projects/fraud_detection
        docker build -t fraud-detection:${{ github.sha }} .
        docker push ${{ secrets.ECR_REGISTRY }}/fraud-detection:${{ github.sha }}
    
    - name: Update EKS deployment
      run: |
        aws eks update-kubeconfig --name fraud-detection-cluster
        kubectl set image deployment/fraud-detection-service \
          fraud-detection=fraud-detection:${{ github.sha }} 