model:
  path: models/fraud_detector.joblib
  threshold: 0.5
  batch_size: 32
  update_frequency: 24  # hours

features:
  numerical:
    - amount
    - hour
    - distance
  categorical:
    - merchant_category
    - merchant_country
  derived:
    - amount_vs_mean
    - time_since_last
    - distance_from_home

monitoring:
  metrics_port: 9090
  log_level: INFO
  alert_threshold: 0.8

database:
  url: postgresql://user:pass@localhost:5432/fraud
  pool_size: 5
  max_overflow: 10

cache:
  url: redis://localhost:6379
  ttl: 3600 