name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    
    - name: Basic repository check
      run: |
        # Check if critical files exist
        test -f README.md
        test -f LICENSE
    
    - name: Repository structure check
      run: |
        # Create basic directory structure if not exists
        mkdir -p projects
        mkdir -p common/{monitoring,deployment,testing}
        mkdir -p docs
        mkdir -p scripts
        mkdir -p templates 