name: CI Pipeline

on:
  push:
    branches: [ main, mlops-repo ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Run tests
      run: |
        for d in projects/*/; do
          cd $d
          if [ -f "setup.py" ]; then
            pip install -e .
            pytest tests/
          fi
          cd ../../
        done