apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-management
  namespace: operations
spec:
  replicas: 3
  selector:
    matchLabels:
      app: inventory-system
  template:
    metadata:
      labels:
        app: inventory-system
    spec:
      containers:
      - name: inventory-service
        image: inventory-service:latest
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: inventory-secrets
              key: database-url
        - name: CACHE_URL
          value: "redis://redis:6379"
        - name: FORECAST_MODEL_PATH
          value: "/models/demand-forecast"
        volumeMounts:
        - name: inventory-storage
          mountPath: /data
        - name: model-storage
          mountPath: /models
      volumes:
      - name: inventory-storage
        persistentVolumeClaim:
          claimName: inventory-data-pvc
      - name: model-storage
        persistentVolumeClaim:
          claimName: model-storage-pvc 